### ISSUE TITLE
iOS 7 issue

### ISSUE THREAD

**Issue by mchicote** [mercadopago/sdk-ios#2]
Hi
I'm having some issues when I try to upload the ipa to TestFlight. Apparently the sdk is not compatible with iOS 7. Here's the error I get:

![screen_shot_2015-06-30_at_6 29 10_pm](https://cloud.githubusercontent.com/assets/1631579/8442572/2d0086cc-1f56-11e5-95b2-27a58a632bc8.png)

Any ideas?

Thanks

pd: @josefermoso

**Comment by EstebanVallejo** [comment]
@mchicote hey, are you still having issues with this ?? I might help a bit with it, the problem may be that you are implementing the SDK via Cocoapods, this way, the SDK is embedded as a static framework (check in the Podfile the line "use_frameworks!" and "platform :ios, '8.0'") . 

It works well when debugging (compiling on your device) because on DEBUG the compiler builds the app only for the active architecture and not for all the possible ones (architectures and operating systems). But for uploading to the AppStore, the compiler builds it for ALL the architectures and OS. And there it fails because it will try to build it for iOS 7 too (I'm assuming you have iOS 8 on your device).

The documentation here says that you should add it manually (not Cocoapods) to use it with iOS 7 and above.

And don't forget to remove the "use_frameworks!" line in your Podfile or it will probably fail with other pods already implemented. (You may need to delete the "Pod" folder, along with the PodLock and <your_project>.workspace, and then do a clean pod install again).

I hope it helps!!

**Comment by mchicote** [comment]
Thanks for your help @EstebanVallejo 
We uploaded the app to the App Store a couple of weeks ago restricting to iOS 8.

**Comment by EstebanVallejo** [comment]
@mchicote  Good! But have in mind that it can work with iOS 7 too! , is a matter of frameworks types, iOS 8 allows Dynamic Frameworks, and iOS 7 and below only Static frameworks.

**Comment by mchicote** [comment]
@EstebanVallejo sure, but there were only a handful of users that where still using iOS 7 so we decided it was a good time to upgrade

**Comment by EstebanVallejo** [comment]
@mchicote Agreed with that! Ok, anyway the answer is there now, just in case some other have the same problem!
